name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install -g htmlhint stylelint
      - name: Lint HTML
        run: htmlhint "src/**/*.html"
      - name: Lint CSS
        run: stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Install Parcel
        run: npm install -g parcel-bundler
      - name: Build Project
        run: parcel build src/index.html --dist-dir build
